---
swagger: "2.0"
info:
  description: "Registo e acompanhamento de encomendas de produtos numa empresa"
  version: "1.0.0"
  title: "Gestor de Encomendas Api"
  termsOfService: "http://localhost:4000/gestorencomendas-api/"
  contact:
    name: "SuporteAI3"
    url: "http://localhost:4000/gestorencomendas-api/v1/termo-uso"
    email: "estgv*****@alunos.estgv.ipv.pt"
host: "localhost:4000"
basePath: "/gestorencomendas-api/v1"
schemes:
- "http"
- "https"
paths:
  /utilizador:
    post:
      tags:
      - "Utilizador"
      summary: "Registar utilizador"
      description: "Registar um novo utilizador"
      operationId: "RegistarUtilizador"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "utilizador_"
        required: true
        schema:
          $ref: "#/definitions/utilizador_"
      responses:
        "201":
          description: "Registo efetuado com sucesso!"
        "204":
          description: "Erro sem conteúdo!"
        "226":
          description: "Erro em uso!"
        "400":
          description: "Requisição inválida!"
        "500":
          description: "Erro interno no servidor!"
      x-swagger-router-controller: "Utilizador"
  /utilizador/{username}:
    get:
      tags:
      - "Utilizador"
      summary: "Buscar utilizador"
      description: "Buscar um utilizador"
      operationId: "BuscarUtilizadorPeloNome"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "Username do utilizador a buscado"
        required: true
        type: "string"
      responses:
        "201":
          description: "Bucado com sucesso!"
          schema:
            $ref: "#/definitions/utilizador_"
        "400":
          description: "Requisição inválida!"
        "404":
          description: "Utilizador não encontrado"
        "500":
          description: "Erro interno no servidor!"
      x-swagger-router-controller: "Utilizador"
    put:
      tags:
      - "Utilizador"
      summary: "Atualizar utilizador"
      description: "Atualizar um utilizador"
      operationId: "AtualizarUtilizador"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "Username do utilizador a ser atualizado"
        required: true
        type: "string"
      - in: "body"
        name: "utilizador_"
        description: "Objeto utilizador atualizado"
        required: true
        schema:
          $ref: "#/definitions/utilizador__1"
      responses:
        "200":
          description: "Atualizado com sucesso!"
        "400":
          description: "Requisição inválida!"
        "404":
          description: "Utilizador não encontrado"
        "500":
          description: "Erro interno no servidor!"
      x-swagger-router-controller: "Utilizador"
  /utilizador/apagar{username}:
    delete:
      tags:
      - "Utilizador"
      summary: "Apagar utilizador"
      description: "Apagar um utilizador"
      operationId: "ApagarUtilizador"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "O nome do utilizador a ser eliminado"
        required: true
        type: "string"
      responses:
        "201":
          description: "Utilizador apagado com sucesso!"
        "204":
          description: "Erro sem conteúdo!"
        "226":
          description: "Erro em uso!"
        "400":
          description: "Nome inválido!"
        "404":
          description: "Utilizador não encontrado!"
        "500":
          description: "Erro interno no servidor!"
      x-swagger-router-controller: "Utilizador"
  /utilizador/login:
    get:
      tags:
      - "Utilizador"
      summary: "Faz o login na API"
      description: "Faz o login na API"
      operationId: "LoginUtilizador"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "Username do utilizador para o login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "Password correspondente ao username"
        required: true
        type: "string"
      responses:
        "200":
          description: "Login efetuado com sucesso!"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
          schema:
            type: "string"
        "400":
          description: "Username e/ou password inválido"
      x-swagger-router-controller: "Utilizador"
    x-swagger-router-controller: "utilizador"
  /utilizador/logout:
    get:
      tags:
      - "Utilizador"
      summary: "Faz o logout da API"
      description: "Faz o logout da API"
      operationId: "LogoutUtilizador"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        default:
          description: "Logout realizado com sucesso"
      x-swagger-router-controller: "Utilizador"
    x-swagger-router-controller: "utilizador"
  /produto:
    post:
      tags:
      - "Produto"
      summary: "Adicionar produto"
      description: "Adicionar um novo produto"
      operationId: "AdicinonarProduto"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "produto_"
        description: "Produto a ser adicionado à loja"
        required: true
        schema:
          $ref: "#/definitions/produto__1"
      responses:
        "201":
          description: "Produto adicionado com sucesso!"
        "204":
          description: "Erro sem conteúdo!"
        "226":
          description: "Erro em uso!"
        "400":
          description: "Requisição inválida!"
        "500":
          description: "Erro interno no servidor!"
      x-swagger-router-controller: "Produto"
    put:
      tags:
      - "Produto"
      summary: "Atualizar um produto"
      description: "Atualizar um produto"
      operationId: "AtualizarProduto"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "produto_"
        description: "Objeto produto a ser atualizado"
        required: true
        schema:
          $ref: "#/definitions/produto_"
      responses:
        "201":
          description: "Atualizado com sucesso!"
        "400":
          description: "Requisição inválida!"
        "404":
          description: "Produto não encontrado"
      x-swagger-router-controller: "Produto"
  /produto/encontrarPorDisp:
    get:
      tags:
      - "Produto"
      summary: "Encontra produto pela disponibilidade"
      description: "Encontra produto pela disponibilidade"
      operationId: "EncontrarProdutoDisp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "disp"
        in: "query"
        description: "Disponibilidade do produto a ser encontrado"
        required: true
        type: "array"
        items:
          type: "string"
          default: "Disponível"
          enum:
          - "Disponível"
          - "Esgotado"
        collectionFormat: "multi"
      responses:
        "200":
          description: "Produto encontrado com sucesso!"
          schema:
            $ref: "#/definitions/inline_response_200"
        "400":
          description: "Produto inválido!"
      x-swagger-router-controller: "Produto"
  /produto/{id_produto}:
    get:
      tags:
      - "Produto"
      summary: "Encontra produto pelo ID"
      description: "Encontra produto pelo ID"
      operationId: "EncontrarProdutoId"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id_produto"
        in: "path"
        description: "ID do produto a ser encontrado"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Produto encontrado com sucesso!"
          schema:
            $ref: "#/definitions/produto__1"
        "400":
          description: "ID do produto inválido!"
        "404":
          description: "Produto não encontrado!"
      x-swagger-router-controller: "Produto"
    delete:
      tags:
      - "Produto"
      summary: "Apaga produto pelo ID"
      description: "Apaga produto pelo ID"
      operationId: "ApagarProdutoId"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id_produto"
        in: "path"
        description: "ID do produto a ser apagado"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Produto apagado com sucesso!"
        "400":
          description: "ID do produto inválido!"
        "404":
          description: "Produto não encontrado!"
      x-swagger-router-controller: "Produto"
  /encomenda:
    post:
      tags:
      - "Encomenda"
      summary: "Registar encomenda"
      description: "Registar uma nova encomenda"
      operationId: "RegistarEncomenda"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "encomenda_"
        description: "Objeto encomenda"
        required: true
        schema:
          $ref: "#/definitions/encomenda__1"
      responses:
        "200":
          description: "Encomenda realizada com sucesso!"
        "400":
          description: "Encomenda inválida!"
      x-swagger-router-controller: "Encomenda"
    put:
      tags:
      - "Encomenda"
      summary: "Atualizar uma encomenda"
      description: "Atualizar uma encomenda"
      operationId: "AtualizarEncomenda"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "encomenda_"
        description: "Objeto encomenda a ser atualizada"
        required: true
        schema:
          $ref: "#/definitions/encomenda_"
      responses:
        "201":
          description: "Atualizado com sucesso!"
        "400":
          description: "Requisição inválida!"
        "404":
          description: "Encomenda não encontrada!"
      x-swagger-router-controller: "Encomenda"
  /encomenda/{id_encomenda}:
    get:
      tags:
      - "Encomenda"
      summary: "Encontrar encomenda pelo ID"
      description: "Encontrar encomenda pelo ID"
      operationId: "EncontrarEncomenda"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id_encomenda"
        in: "path"
        description: "ID da encomenda a encontrar"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Encomenda encontrada com sucesso!"
          schema:
            $ref: "#/definitions/encomenda__1"
        "400":
          description: "ID da encomenda invalido!"
        "404":
          description: "Encomenda não encontrada!"
      x-swagger-router-controller: "Encomenda"
definitions:
  produto__1:
    type: "object"
    properties:
      id_produto:
        type: "integer"
        example: 1
      nome:
        type: "string"
        example: "Leite"
      tipo:
        type: "string"
        example: "alimento"
      preço:
        type: "number"
        format: "double"
      descrição:
        type: "string"
      disp:
        type: "string"
        enum:
        - "Disponível"
        - "Esgotado"
      stock:
        type: "integer"
        format: "int32"
    example:
      tipo: "alimento"
      descrição: "descrição"
      preço: 0.80082819046101150206595775671303272247314453125
      nome: "Leite"
      stock: 6
      id_produto: 1
      disp: "Disponível"
  encomenda__1:
    type: "object"
    properties:
      id_encomenda:
        type: "integer"
        example: 1
      estado:
        type: "string"
        enum:
        - "Criada"
        - "Enviada"
        - "Cancelada"
        - "Entregue"
      data_cria:
        type: "string"
        format: "date"
      password:
        type: "string"
      username:
        type: "string"
      datanasc:
        type: "string"
        format: "date"
    example:
      estado: "Criada"
      password: "password"
      data_cria: "2000-01-23"
      datanasc: "2000-01-23"
      id_encomenda: 1
      username: "username"
  utilizador__1:
    type: "object"
    properties:
      id_funcionario:
        type: "integer"
        example: 1
      funcionario:
        type: "string"
        example: "Janete Silva"
      email:
        type: "string"
        example: "janete@silva.com"
      password:
        type: "string"
      username:
        type: "string"
      datanasc:
        type: "string"
        format: "date"
  utilizador_:
    type: "object"
    properties:
      id_funcionario:
        type: "integer"
        example: 1
      funcionario:
        type: "string"
        example: "Janete Silva"
      email:
        type: "string"
        example: "janete@silva.com"
      password:
        type: "string"
      username:
        type: "string"
      datanasc:
        type: "string"
        format: "date"
    example:
      password: "password"
      datanasc: "2000-01-23"
      id_funcionario: 1
      funcionario: "Janete Silva"
      email: "janete@silva.com"
      username: "username"
  inline_response_200:
    type: "object"
    properties:
      id_produto:
        type: "integer"
        example: 1
      nome:
        type: "string"
        example: "Leite"
      tipo:
        type: "string"
        example: "alimento"
      preço:
        type: "number"
        format: "double"
      descrição:
        type: "string"
      disp:
        type: "string"
        enum:
        - "Disponível"
        - "Esgotado"
      stock:
        type: "integer"
        format: "int32"
        example: 4
    example:
      tipo: "alimento"
      descrição: "descrição"
      preço: 0.80082819046101150206595775671303272247314453125
      nome: "Leite"
      stock: 4
      id_produto: 1
      disp: "Disponível"
  produto_:
    type: "object"
    properties:
      id_produto:
        type: "integer"
        example: 1
      nome:
        type: "string"
        example: "Leite"
      tipo:
        type: "string"
        example: "alimento"
      preço:
        type: "number"
        format: "double"
      descrição:
        type: "string"
      disp:
        type: "string"
        enum:
        - "Disponível"
        - "Esgotado"
      stock:
        type: "integer"
        format: "int32"
  encomenda_:
    type: "object"
    properties:
      id_encomenda:
        type: "integer"
        example: 1
      estado:
        type: "string"
        enum:
        - "Criada"
        - "Enviada"
        - "Cancelada"
        - "Entregue"
      data_cria:
        type: "string"
        format: "date"
      password:
        type: "string"
      username:
        type: "string"
      datanasc:
        type: "string"
        format: "date"
